language: node_js

node_js:
  - v7

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.electron

script:
  - npm run lint

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then npm run build && npm run package; fi;

deploy:
  provider: releases
  api_key:
    secure: EiK2mTXR/+13tRnsxG3YmDoEk5A5wPkofJimAkDmcPcNCzxPy+517SKaVuxAH1XafSm+L3mAEhK6pCQ3PxMERJKQqk7TwLuHde3TBW2fzaN02UVven31tCcJWKAMl3Wa1xPMO8s5Lwk6gaXMxNYzZ90/5KtQqt+jvB67PyNB8PSqfaGrtZS2laPfvbi2cF6V737/w+Xb9QiFy0Ke+1xQvtraMlGT2MVdjb9WCgqh8cWyU3UbIEauQCXgDMFZ7Ve9UWQWyvUVwG8dXltPs1IWl1eOBrjlLv7jekeZb5hID0QztBBQPwJfypf+dVXiR6pm4KJbOihx8h+MkIIZMdPuO0Vh2DTTlHuEwzHnrXL9FQZV1zlGMO7klzQBtx5Jk3W4yakuGFHQvuZb7AHiXkwnGJdoIDPZr5TsP4qe0Z0EjKpo7WrZej8/UyO5y+cZdv3vOKcnSrhm4fzjqE3GAs71zKjtwQvW9pC1zyvBzeqCphJaxvL8c1fu2qP1zTZu+9UEdlAeQem6xa6BbWzObTdtICS2kjmLS7ukct2Ap4WqRbzhthsw88tb7CGBPeowgNQUgebXSss0GZywhYP84vQFCHRcxJ5YJ6GtSIphQNOpo37FlppQpTml84GSHCCs9xnyTw7wBIuJpaLMyNpTWD0XV8Xf/PEvnYCGT8AWtKCcYbA=
  file_glob: true
  file: dist/*.tar.bz2
  skip_cleanup: true
  on:
    tags: true
