language: node_js

node_js:
  - stable

sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    - secure: bNuSD0H9X2DbkgY9GJbJnnTJ/TT+ugOY/47Gp4zvFLYeMPm8jdXHRm+lBWMeQNDdDYuHj790kcSsj5Isqk2AaAzUfCf5EsOXDYF8PwL3O80/kXf6k4YskQ+aziVx1pbgFHbb2LasmsbRN6jbB+NMM3ZO4ifW79JmkYV42RyfYKjKvreerOCImhyOs1jRKkWyYYDkoC1tuPaod9lwY4QTxWTXlWSyniQJpImEh7YPum1wm6ceFxKKNgsC+Hs0jGwTskQqNG73MlCBucnE3z/bBQXg3Yu4rYYNoeLsrt7xqlKKlvTu9bvu9x0s7evekycwKyjjJAVFvi+bcXxsaka/VFkYogujp3rSHyXR1H+O+qkJBPGqQxvS/OEv+nEqvwLwy63brNvtR93xqCrn6dFtrlamY8H8gkAaFvC0g3B/kXHUjEUT5QdhA48q9vjDzQH/sSOLSA5dEtGjkANfiXdu4yABhM+ys6hpusD/3XAB/UpbdKnnyocUCimiMNtBlhngG1ArqJNfk8uLurVCaIJTQwrL2HMcHRGnVVjQCZTPFfs31mmuiW243kKuUjDZwAADk1vf8ie3riy4WEH8aAJnJeGhr0HNvghmXRj5JII2GOwFPXngU3P2aKFwat9Cfd1lpXIZncs4sGnyrZqNPcv+V3vRXOpJW6dSpBSpwYZCY6k=

script:
  - npm run lint
  - npm run build
  - npm run package

after_script:
  - npm run ci:release
